### ISSUE TITLE
node not loading

### ISSUE THREAD

**Issue by canochento** [uarefans/ComfyUI-Fans#1]
i was loading a pre existing workflow, but i have this node missing, and comfy is giving me this error

[ERROR] An error occurred while retrieving information for the 'Fans Styler' node.
Traceback (most recent call last):
  File "D:\Git\ComfyUI_windows_portable\ComfyUI\server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\Git\ComfyUI_windows_portable\ComfyUI\server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Fans\py\Styler.py", line 42, in INPUT_TYPES
    cls.styles1 = [row for row in reader if len(row) == 2 and row[1] != "prompt" and row[0] != "None"]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Fans\py\Styler.py", line 42, in <listcomp>
    cls.styles1 = [row for row in reader if len(row) == 2 and row[1] != "prompt" and row[0] != "None"]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence

**Comment by Yuriuori** [comment]
i also have the same problem

**Comment by uarefans** [comment]
Thank to waiting and sorry for late reply, 
please put your workflow here so i can reproduce your error

**Comment by uarefans** [comment]
1. I try to reproduce your issue with
2. try change style1.csv content (title, desc) with japanese character then i get error
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 32: character maps to <undefined>
Maybe is not the same, but my styler is error too

3. But i try to fix it with add with open(csv_file_path1, "r", encoding="utf-8") as f:
4. Error is gone, and i can put japanese character in boot title and desc
5. For details can check, resolve issue with new update https://github.com/uarefans/ComfyUI-Fans/commit/3c6f482fb261ade093876dc32f4a8804675d743f
6. please git pull in your custom_nodes/comfy_fans for get new update, no need install anything

please open this issue again if you still get error, thank you
